### ISSUE TITLE
ModuleNotFoundError: No module named 'simulation'

### ISSUE THREAD

**Issue by xkuan** [ingambe/RL4SemiconductorFabSched#1]
Thank you for your sharing, which will be of great help to my research.

I would like to ask how to solve this problem when I run `parallel_dispatch_greedy.py` ?
```
output_iter = ray.get(
        [
            one_pop_iter.remote(k, run_to, a.dataset)
            for k in range(nb_workers)
        ]
    )
```

Thanks a lot!

**Comment by ingambe** [comment]
Hi!
It seems like the problem is due to the PYTHONPATH variable.
It could be helpful to include the source directory in the python path:

`export PYTHONPATH="${PYTHONPATH}:/my/other/path"`

**Comment by xkuan** [comment]
That's the problem! Thank you very much!

**Comment by WayneHsiao0225** [comment]
About PYTHONPATH setting, what should I set this path point to ? thanks.
@ingambe
