### ISSUE TITLE
Data Processing

### ISSUE THREAD

**Issue by xkuan** [ingambe/RL4SemiconductorFabSched#2]
Hi! I'm back!
Is there a data processing part of the repo?  Maybe the process from txt files in "datasets" to pkl files?

**Comment by ingambe** [comment]
Hi,
Not really, the code to compute the lot feature representation is here:
[https://github.com/ingambe/RL4SemiconductorFabSched/blob/89467c6a14931a8e9e33f66af29b91b1ed72f929/simulation/es/train_es.py#L174C16-L174C16](https://github.com/ingambe/RL4SemiconductorFabSched/blob/89467c6a14931a8e9e33f66af29b91b1ed72f929/simulation/es/train_es.py#L174C16-L174C16)

The pkl files contain a snapshot of the fab after 1 year of run (i.e., the goal is not to start with an empty fab, which is unrealistic, but a fab with machines already busy with setup on them, maintenances, breakdowns, etc...)
You can generate your own pkl by simply adding a code to pickle the simulator after X days of simulation using the greedy heuristic

**Comment by xkuan** [comment]
Oh, I got it!
Thanks for your patient reply!
